driver:
  name: vagrant
  vagrantfile_erb: templates/Vagrantfile.erb
  provider: ovirt4

verifier:
  name: inspec
  format: doc

platforms:
  - name: centos7
    driver_plugin: vagrant
    driver_config:
      customize:
        memory_size: 1024 MB
        url: <%= ENV['OVIRT_URL'] %>
        insecure: true
        username: <%= ENV['OVIRT_USERNAME'] %>
        password: <%= ENV['OVIRT_PASSWORD'] %>
        cluster: Default
        debug: true
      box: ovirt4
      box_url: https://github.com/myoung34/vagrant-ovirt4/blob/master/example_box/dummy.box?raw=true

suites:
  - name: static_network
    driver_config:
      vm_hostname: static
      customize:
        template: vagrant-centos7
      network:
        - ["private_network", {ovirt__ip: <%= "192.168.2.#{Random.rand(240..254)}" %>, ovirt__network_name: 'ovirtmgmt', ovirt__gateway: 192.168.2.1, ovirt__netmask: 255.255.255.0, ovirt__dns_servers: 192.168.2.1}]
  - name: dynamic_network
    driver_config:
      vm_hostname: dynamic
      network:
        - ["private_network", {ovirt__network_name: 'ovirtmgmt'}]
      customize:
        template: vagrant-centos7
        cloud_init: |
          runcmd:
            - ifdown eth0
            - service network restart
